
export interface NewsItem {
  id: string;
  category: 'Mercado' | 'Regulación' | 'Consejo' | 'Tendencia' | 'Inversión';
  headline: { es: string; en: string };
  body: { es: string; en: string };
  date: string;
  source: 'Analistas Rentia' | 'Mercado Murcia' | 'Noticias Sector' | 'BCE' | 'Idealista Data';
}

export const newsDatabase: NewsItem[] = [
  // NOVIEMBRE - DICIEMBRE 2024
  {
    id: 'n1',
    category: 'Mercado',
    headline: {
      es: 'La demanda de habitaciones en Murcia crece un 15% en el último trimestre de 2024.',
      en: 'Room demand in Murcia grows by 15% in the last quarter of 2024.'
    },
    body: {
      es: 'Según los últimos datos cruzados de los principales portales inmobiliarios y nuestra propia base de datos en RentiaRoom, la demanda de alojamiento compartido en Murcia capital ha experimentado un repunte del 15% interanual. Este fenómeno se atribuye principalmente a la escasez de oferta de alquiler tradicional de vivienda completa, que empuja a jóvenes profesionales y parejas a optar por el alquiler de habitaciones premium como solución habitacional a medio plazo.',
      en: 'According to cross-referenced data from major real estate portals and our own database at RentiaRoom, demand for shared accommodation in Murcia city has seen a 15% year-on-year increase. This phenomenon is mainly attributed to the scarcity of traditional whole-home rental supply, pushing young professionals and couples to opt for premium room rentals as a medium-term housing solution.'
    },
    date: '15 Nov 2024',
    source: 'Mercado Murcia'
  },
  {
    id: 'n2',
    category: 'Regulación',
    headline: {
      es: 'Propietarios migran al alquiler de temporada para evitar topes de precios.',
      en: 'Landlords migrate to seasonal rentals to avoid price caps.'
    },
    body: {
      es: 'Ante la incertidumbre generada por la aplicación de la Ley de Vivienda en ciertas comunidades y el temor a futuras regulaciones en la Región de Murcia, un número significativo de pequeños propietarios está trasladando sus activos del mercado residencial convencional al mercado de temporada (alquiler por habitaciones o contratos inferiores a 11 meses). Esta modalidad, regida por el Código Civil y no por la LAU en términos de duración, ofrece mayor seguridad jurídica y flexibilidad para recuperar la vivienda.',
      en: 'Given the uncertainty generated by the Housing Law application in certain regions and fear of future regulations in Murcia, a significant number of small owners are moving their assets from the conventional residential market to the seasonal market (room rentals or contracts under 11 months). This modality, governed by the Civil Code rather than the LAU in terms of duration, offers greater legal security and flexibility to recover the property.'
    },
    date: '18 Nov 2024',
    source: 'Noticias Sector'
  },
  {
    id: 'n3',
    category: 'Inversión',
    headline: {
      es: 'El barrio del Carmen: Zona de mayor rentabilidad bruta en Q4 2024.',
      en: 'El Carmen neighborhood: Highest gross yield area in Q4 2024.'
    },
    body: {
      es: 'Nuestro equipo de analistas ha identificado el Barrio del Carmen como el "punto caliente" de inversión para finalizar el año. Con precios de compra por metro cuadrado aún contenidos en comparación con la zona norte, y una demanda de alquiler fortísima gracias a la cercanía a la estación de tren y al centro, las rentabilidades brutas están superando el 9% en pisos reformados y adaptados para el alquiler por habitaciones.',
      en: 'Our analyst team has identified Barrio del Carmen as the investment "hotspot" to end the year. With purchase prices per square meter still contained compared to the north zone, and very strong rental demand due to proximity to the train station and center, gross yields are exceeding 9% in renovated apartments adapted for room rentals.'
    },
    date: '20 Nov 2024',
    source: 'Analistas Rentia'
  },
  {
    id: 'n4',
    category: 'Tendencia',
    headline: {
      es: 'El perfil "Nómada Digital" busca habitaciones premium en Murcia centro.',
      en: '"Digital Nomad" profile seeks premium rooms in Murcia center.'
    },
    body: {
      es: 'Murcia empieza a posicionarse como destino atractivo para teletrabajadores nacionales y extranjeros. Este perfil no busca un piso compartido de estudiantes convencional. Exigen habitaciones con cama doble, escritorio ergonómico, aire acondicionado y, sobre todo, una conexión a internet de alta velocidad simétrica. Los propietarios que adaptan sus viviendas a este estándar están logrando rentas un 20% superiores a la media.',
      en: 'Murcia is starting to position itself as an attractive destination for domestic and foreign remote workers. This profile does not seek a conventional student shared apartment. They demand rooms with double beds, ergonomic desks, air conditioning, and above all, a symmetric high-speed internet connection. Owners who adapt their homes to this standard are achieving rents 20% above average.'
    },
    date: '22 Nov 2024',
    source: 'Idealista Data'
  },
  
  // INICIOS 2025 (Q1)
  {
    id: 'n5',
    category: 'Inversión',
    headline: {
      es: 'Previsión 2025: Estabilización de tipos al 2,5% reactivará la compra para reforma.',
      en: '2025 Forecast: Rate stabilization at 2.5% will reactivate purchase for renovation.'
    },
    body: {
      es: 'El Banco Central Europeo da señales de una política monetaria más suave para el próximo ejercicio. Se espera que los tipos de interés se estabilicen en el entorno del 2,5% durante 2025. Esto abaratará las hipotecas y, previsiblemente, reactivará la demanda de compra de viviendas de segunda mano para reformar y destinar al alquiler, aumentando la competencia entre inversores.',
      en: 'The European Central Bank signals a softer monetary policy for the next year. Interest rates are expected to stabilize around 2.5% during 2025. This will lower mortgages and, predictably, reactivate demand for purchasing second-hand homes to renovate and rent out, increasing competition among investors.'
    },
    date: '02 Ene 2025',
    source: 'BCE'
  },
  {
    id: 'n6',
    category: 'Mercado',
    headline: {
      es: 'Récord histórico de solicitudes internacionales en la UCAM para enero 2025.',
      en: 'Historic record of international applications at UCAM for January 2025.'
    },
    body: {
      es: 'La Universidad Católica de Murcia (UCAM) reporta cifras récord de preinscripciones de estudiantes internacionales para el segundo cuatrimestre del curso. Esto generará un pico de demanda de alojamiento en enero y febrero, especialmente en las zonas de Guadalupe, La Ñora y el centro de Murcia (con buena conexión de tranvía). Se recomienda a los propietarios tener disponibilidad lista para estas fechas.',
      en: 'The Catholic University of Murcia (UCAM) reports record pre-enrollment figures for international students for the second semester. This will generate a peak in accommodation demand in January and February, especially in Guadalupe, La Ñora, and Murcia center (with good tram connection). Owners are advised to have availability ready for these dates.'
    },
    date: '10 Ene 2025',
    source: 'Mercado Murcia'
  },
  {
    id: 'n7',
    category: 'Consejo',
    headline: {
      es: 'El Aire Acondicionado aumenta el valor del alquiler un 12%.',
      en: 'Air Conditioning increases rental value by 12%.'
    },
    body: {
      es: 'En una ciudad con la climatología de Murcia, la climatización ha dejado de ser un lujo para convertirse en una necesidad básica. Nuestro análisis de cartera muestra que las habitaciones equipadas con Split de aire acondicionado individual se alquilan un 12% más caras y reducen el tiempo de vacancia en verano en un 40% respecto a las que solo tienen ventilador.',
      en: 'In a city with Murcia\'s climate, air conditioning has gone from luxury to basic necessity. Our portfolio analysis shows that rooms equipped with individual Split air conditioning rent for 12% more and reduce summer vacancy time by 40% compared to those with only fans.'
    },
    date: '15 Feb 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n8',
    category: 'Regulación',
    headline: {
      es: 'Nuevas deducciones fiscales para rehabilitación de vivienda en Murcia.',
      en: 'New tax deductions for housing rehabilitation in Murcia.'
    },
    body: {
      es: 'El gobierno regional ha aprobado un nuevo paquete de medidas fiscales para 2025 que incluye deducciones en el tramo autonómico del IRPF para aquellos propietarios que realicen obras de mejora energética y accesibilidad en viviendas destinadas al alquiler para jóvenes menores de 35 años.',
      en: 'The regional government has approved a new package of tax measures for 2025 that includes deductions in the regional income tax bracket for owners who carry out energy improvement and accessibility works in homes intended for rental to young people under 35 years old.'
    },
    date: '28 Feb 2025',
    source: 'Noticias Sector'
  },

  // MEDIADOS 2025 (Q2 - Q3)
  {
    id: 'n9',
    category: 'Tendencia',
    headline: {
      es: 'El "Coliving" híbrido gana terreno en el mercado.',
      en: 'Hybrid "Coliving" gains ground in the market.'
    },
    body: {
      es: 'El concepto de Coliving se está democratizando. Ya no es necesario un edificio entero operado por una gran empresa. Los pisos compartidos "híbridos", que ofrecen servicios añadidos como limpieza semanal incluida, cuentas de streaming compartidas (Netflix/HBO) y suministros con tarifa plana, se están alquilando en menos de 48 horas frente a las semanas que tardan los pisos tradicionales.',
      en: 'The Coliving concept is democratizing. An entire building operated by a large company is no longer necessary. "Hybrid" shared apartments, offering added services like included weekly cleaning, shared streaming accounts (Netflix/HBO), and flat-rate utilities, are renting in less than 48 hours compared to weeks for traditional apartments.'
    },
    date: '15 Mar 2025',
    source: 'Idealista Data'
  },
  {
    id: 'n10',
    category: 'Mercado',
    headline: {
      es: 'Juan Carlos I dispara precios superando los 400€/mes por habitación.',
      en: 'Juan Carlos I prices skyrocket exceeding €400/month per room.'
    },
    body: {
      es: 'La zona norte de Murcia sigue su escalada de precios. La calidad de las edificaciones, la seguridad y la conexión con el tranvía han convertido a Juan Carlos I en la "milla de oro" del alquiler por habitaciones. Las habitaciones con baño privado en esta zona ya están rompiendo la barrera de los 400€ mensuales de renta base.',
      en: 'The northern area of Murcia continues its price climb. The quality of buildings, security, and tram connection have turned Juan Carlos I into the "golden mile" of room rentals. Rooms with private bathrooms in this area are already breaking the €400 monthly base rent barrier.'
    },
    date: '10 Abr 2025',
    source: 'Mercado Murcia'
  },
  {
    id: 'n11',
    category: 'Inversión',
    headline: {
      es: 'Pisos sin ascensor céntricos sufren corrección: Oportunidad de Cashflow.',
      en: 'Central apartments without elevators suffer correction: Cashflow Opportunity.'
    },
    body: {
      es: 'Mientras la obra nueva sube, la segunda mano sin ascensor (especialmente terceras y cuartas plantas) está sufriendo una corrección de precio a la baja. Para el inversor enfocado en rentabilidad (cashflow) y no en revalorización, esto representa una oportunidad única: comprar barato en zonas prime y alquilar a estudiantes jóvenes a los que no les importa subir escaleras.',
      en: 'While new construction rises, second-hand apartments without elevators (especially third and fourth floors) are suffering a downward price correction. For investors focused on yield (cashflow) rather than appreciation, this represents a unique opportunity: buy cheap in prime areas and rent to young students who don\'t mind climbing stairs.'
    },
    date: '05 May 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n12',
    category: 'Regulación',
    headline: {
      es: 'Endurecimiento de licencias turísticas desvía inversión al alquiler de temporada.',
      en: 'Tightening of tourist licenses diverts investment to seasonal rentals.'
    },
    body: {
      es: 'Ante los rumores y borradores de normativas municipales que planean restringir severamente las nuevas licencias de Vivienda de Uso Turístico (VUT) en el centro de Murcia, muchos inversores están pivotando su modelo de negocio hacia el alquiler de media estancia (habitaciones), que ofrece rentabilidades similares con mucha menos carga operativa y regulatoria.',
      en: 'Given rumors and drafts of municipal regulations planning to severely restrict new Tourist Use Housing (VUT) licenses in central Murcia, many investors are pivoting their business model towards mid-term rentals (rooms), which offer similar yields with much less operational and regulatory burden.'
    },
    date: '20 May 2025',
    source: 'Noticias Sector'
  },

  // FUTURO 2025 (Q4)
  {
    id: 'n13',
    category: 'Mercado',
    headline: {
      es: 'Stock de alquiler tradicional podría reducirse un 20% adicional.',
      en: 'Traditional rental stock could shrink by an additional 20%.'
    },
    body: {
      es: 'Las proyecciones para finales de 2025 indican una fuga continua de inventario del mercado de alquiler residencial de larga duración. Si la inseguridad jurídica para el propietario no se resuelve, estimamos que el stock disponible para familias se reducirá un 20% más, trasladándose a la venta o al alquiler temporal.',
      en: 'Projections for late 2025 indicate a continued inventory flight from the long-term residential rental market. If legal insecurity for landlords is not resolved, we estimate available stock for families will reduce by another 20%, shifting to sales or temporary rentals.'
    },
    date: '01 Sep 2025',
    source: 'Idealista Data'
  },
  {
    id: 'n14',
    category: 'Inversión',
    headline: {
      es: 'Alcantarilla y El Palmar: Las nuevas "ciudades dormitorio" rentables.',
      en: 'Alcantarilla and El Palmar: The new profitable "dormitory towns".'
    },
    body: {
      es: 'Con los precios de Murcia capital tensionados, la demanda se desplaza al área metropolitana. Alcantarilla y El Palmar, gracias a sus excelentes conexiones de autobús y servicios propios, están emergiendo como plazas muy rentables para la inversión, con precios de compra un 30-40% inferiores a la capital pero rentas de alquiler muy robustas.',
      en: 'With strained prices in Murcia city, demand shifts to the metropolitan area. Alcantarilla and El Palmar, thanks to excellent bus connections and their own services, are emerging as very profitable investment locations, with purchase prices 30-40% lower than the capital but very robust rental income.'
    },
    date: '15 Sep 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n15',
    category: 'Tendencia',
    headline: {
      es: 'Digitalización total: Contratos y visitas virtuales.',
      en: 'Total digitalization: Contracts and virtual tours.'
    },
    body: {
      es: 'La visita física está perdiendo peso. Más del 60% de las reservas de habitaciones para el curso 2025-2026 se están cerrando mediante "recorridos virtuales" o videollamadas, y la firma de contratos es ya casi 100% digital. El propietario que no ofrece estas facilidades pierde competitividad, especialmente con el inquilino internacional.',
      en: 'Physical visits are losing weight. More than 60% of room bookings for the 2025-2026 academic year are closing via "virtual tours" or video calls, and contract signing is almost 100% digital. Owners not offering these facilities lose competitiveness, especially with international tenants.'
    },
    date: '01 Oct 2025',
    source: 'Mercado Murcia'
  },

  // EXTRAS
  {
    id: 'n16',
    category: 'Consejo',
    headline: {
      es: 'El Código Civil protege mejor al propietario en alquiler de temporada.',
      en: 'The Civil Code better protects the owner in seasonal rentals.'
    },
    body: {
      es: 'Es fundamental entender la diferencia legal. Mientras la LAU protege la necesidad de vivienda permanente, el Código Civil regula el arrendamiento de cosas por tiempo determinado. Alquilar por temporada (con causa justificada como estudios o trabajo temporal) permite recuperar la vivienda al fin del contrato sin prórrogas forzosas de 5 años.',
      en: 'Understanding the legal difference is crucial. While LAU protects permanent housing needs, the Civil Code regulates the leasing of things for a determined time. Renting seasonally (with justified cause like studies or temporary work) allows recovering the home at contract end without mandatory 5-year extensions.'
    },
    date: '12 Oct 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n17',
    category: 'Mercado',
    headline: {
      es: 'La rentabilidad media del alquiler por habitaciones supera el 8,5%.',
      en: 'Average room rental yield exceeds 8.5%.'
    },
    body: {
      es: 'A pesar de la inflación en los costes de suministros y reformas, el alquiler por habitaciones sigue siendo el rey de la rentabilidad inmobiliaria en Murcia, ofreciendo un retorno neto medio superior al 8,5%, muy por encima de letras del tesoro, bolsa o alquiler tradicional.',
      en: 'Despite inflation in utility and renovation costs, room rental remains the king of real estate profitability in Murcia, offering an average net return exceeding 8.5%, well above treasury bills, stock market, or traditional rentals.'
    },
    date: '20 Oct 2025',
    source: 'Idealista Data'
  },
  {
    id: 'n18',
    category: 'Inversión',
    headline: {
      es: 'Hipotecas "Buy to Rent": La banca se adapta al inversor.',
      en: '"Buy to Rent" Mortgages: Banks adapt to the investor.'
    },
    body: {
      es: 'Varias entidades bancarias están lanzando productos específicos para inversores inmobiliarios, que tienen en cuenta no solo los ingresos por nómina del solicitante, sino también la rentabilidad esperada del activo a adquirir para conceder la financiación. Esto facilitará el apalancamiento en 2025.',
      en: 'Several banks are launching specific products for real estate investors, taking into account not only the applicant\'s payroll income but also the expected profitability of the asset to be acquired to grant financing. This will facilitate leverage in 2025.'
    },
    date: '05 Nov 2025',
    source: 'BCE'
  },
  {
    id: 'n19',
    category: 'Tendencia',
    headline: {
      es: 'Home Staging Virtual para pre-comercializar reformas.',
      en: 'Virtual Home Staging to pre-market renovations.'
    },
    body: {
      es: 'Ya no hace falta esperar a terminar la obra para anunciar el piso. El uso de renders fotorrealistas y Home Staging Virtual permite firmar contratos de alquiler meses antes de que la reforma esté terminada, eliminando los tiempos muertos de vacancia post-obra.',
      en: 'You no longer have to wait to finish the work to advertise the apartment. The use of photorealistic renders and Virtual Home Staging allows signing rental contracts months before the renovation is finished, eliminating post-work vacancy downtime.'
    },
    date: '15 Nov 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n20',
    category: 'Mercado',
    headline: {
      es: 'Habitaciones con baño privado: +20% de precio.',
      en: 'Rooms with private bath: +20% price.'
    },
    body: {
      es: 'La privacidad es el nuevo lujo. La diferencia de precio entre una habitación estándar y una tipo "suite" con baño privado se ha ampliado hasta el 20%. En reformas integrales, priorizar sacar un baño extra es la decisión más rentable que puede tomar un inversor.',
      en: 'Privacy is the new luxury. The price difference between a standard room and a "suite" type with private bathroom has widened to 20%. In comprehensive renovations, prioritizing an extra bathroom is the most profitable decision an investor can make.'
    },
    date: '25 Nov 2025',
    source: 'Mercado Murcia'
  },
  {
    id: 'n21',
    category: 'Regulación',
    headline: {
      es: 'Hacienda y el control del alquiler no declarado.',
      en: 'Tax Agency and control of undeclared rentals.'
    },
    body: {
      es: 'La Agencia Tributaria cruzará datos de consumo eléctrico y plataformas digitales para detectar alquileres sumergidos. La gestión profesional a través de empresas como RentiaRoom garantiza el cumplimiento fiscal y evita sanciones, además de permitir la deducción correcta de todos los gastos operativos.',
      en: 'The Tax Agency will cross-reference electricity consumption data and digital platforms to detect underground rentals. Professional management through companies like RentiaRoom guarantees tax compliance and avoids sanctions, as well as allowing the correct deduction of all operating expenses.'
    },
    date: '01 Dic 2025',
    source: 'Noticias Sector'
  },
  {
    id: 'n22',
    category: 'Consejo',
    headline: {
      es: 'Internet de 1Gb: Requisito no negociable.',
      en: '1Gb Internet: Non-negotiable requirement.'
    },
    body: {
      es: 'Hace años, el WiFi era un extra. Hoy es tan importante como el agua caliente. Para atraer a perfiles de calidad (estudiantes de máster, trabajadores), una conexión doméstica básica no sirve. Se requiere fibra de alta velocidad y buena cobertura en todas las estancias.',
      en: 'Years ago, WiFi was an extra. Today it is as important as hot water. To attract quality profiles (master students, workers), a basic domestic connection does not work. High-speed fiber and good coverage in all rooms are required.'
    },
    date: '10 Dic 2025',
    source: 'Analistas Rentia'
  },
  {
    id: 'n23',
    category: 'Inversión',
    headline: {
      es: 'Espinardo: Rey de la rentabilidad estudiantil.',
      en: 'Espinardo: King of student profitability.'
    },
    body: {
      es: 'A pesar del auge de otras zonas, Espinardo mantiene su corona gracias a la proximidad física al Campus de la UMU. La demanda es constante y masiva, lo que garantiza una ocupación del 100% durante el curso académico con un esfuerzo de marketing mínimo.',
      en: 'Despite the rise of other areas, Espinardo keeps its crown thanks to physical proximity to the UMU Campus. Demand is constant and massive, guaranteeing 100% occupancy during the academic year with minimal marketing effort.'
    },
    date: '15 Dic 2025',
    source: 'Mercado Murcia'
  },
  {
    id: 'n24',
    category: 'Mercado',
    headline: {
      es: 'Tiempo medio de ocupación baja a 7 días.',
      en: 'Average occupancy time drops to 7 days.'
    },
    body: {
      es: 'La velocidad del mercado es vertiginosa. Una habitación bien presentada y con precio de mercado en Murcia capital tarda una media de solo 7 días en alquilarse desde su publicación. En RentiaRoom, gracias a nuestra lista de espera, a menudo cerramos el alquiler en menos de 24 horas.',
      en: 'Market speed is dizzying. A well-presented room at market price in Murcia city takes an average of only 7 days to rent from publication. At RentiaRoom, thanks to our waiting list, we often close rentals in less than 24 hours.'
    },
    date: '20 Dic 2025',
    source: 'Idealista Data'
  },
  {
    id: 'n25',
    category: 'Tendencia',
    headline: {
      es: 'Auge del "Rent to Rent" para pequeños inversores.',
      en: 'Rise of "Rent to Rent" for small investors.'
    },
    body: {
      es: 'El modelo de subarriendo autorizado (Rent to Rent) está permitiendo a pequeños emprendedores entrar en el sector inmobiliario sin necesidad de comprar activos. Gestionan propiedades de terceros garantizándoles una renta, y obtienen su beneficio de la optimización del alquiler por habitaciones.',
      en: 'The authorized subletting model (Rent to Rent) is allowing small entrepreneurs to enter the real estate sector without buying assets. They manage third-party properties guaranteeing them a rent, and obtain their profit from optimizing room rentals.'
    },
    date: '28 Dic 2025',
    source: 'Noticias Sector'
  }
];
